language: node_js
node_js:
  - "lts/*"
stages:
  - lint
  - test
  - build
  - compile
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: compile
      script: yarn compile
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test